local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

site_url: https://magis-data-intelligence.nl
display_url: https://magis-data-intelligence.nl
logo_url: /favicon.svg

collections:
  - name: blog
    label: Blog
    label_singular: Artikel
    folder: content/blog
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Publicatiedatum, name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: Intro, name: excerpt, widget: text }
      - { label: Omslagbeeld, name: cover, widget: image, required: false }
      - label: Tags
        name: tags
        widget: list
        collapsed: false
        field: { label: Tag, name: tag, widget: string }
      - { label: Uitgelicht op homepage, name: featured, widget: boolean, required: false, default: false }
      - { label: Inhoud, name: body, widget: markdown }
